import type { Metadata } from 'next'
import { gibson } from '@/styles/font'
import '../styles/tailwind.css'
import clsx from 'clsx'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(gibson.className, "relative")}>{children}</body>
    </html>
  )
}
